name: skychat
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  skynet:
    path: ../skynet
  convert: ^3.0.0
  simple_observable: ^2.0.0
  collection: ^1.15.0
  intl: ^0.17.0
  string_validator: ^0.3.0
#  path: ^1.7.0
dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0

